### PR TITLE
Python3.6 alfacoins library

### PR DESCRIPTION
**Pull request by iRhonin**

### CODE REVIEW

**Comment by ALFAcoins** [comment]
Hi!

Thank you for your API developer contest entry!

Few things before we accept this pull request:
1. No need to delete `super_developer_example.md` file in your commit
2. There is an error when using `alfacoins = ALFACoins()` without parameters:
`@password.setter - couldn't encode('utf-8') of None`
3. `alfacoins.get_rates()['BTC']` is not very useful method to provide rates. Basically to search for certain currency code you need to use extra function: ```
[{'code': 'AED', 'rate': 13500.162957}, {'code': 'AFN', 'rate': 277689.53825}, .. ]
``` Please use https://www.alfacoins.com/developers#get_requests-ratesdict method and parse rates as dict instead. It would be great to get rates like this: `alfacoins.get_rates()['BTC']['USD']`
4. `alfacoins.get_rate('BTC_USD')` returns list instead of the number: ['3675.50000000']
5. What about python package managers? Is it possible to integrate your package into e.g. pypi.org or any other python package list and add installation instructions into README as well. 

Thanks a lot!

**Comment by iRhonin** [comment]
Hi 
Thank you a lot for your response :)

And about your feedbacks:

1.  Should I restore it?. 
2. Fixed. https://github.com/ArashFatahzade/alfacoins/commit/0aefc26b85b8c1884e92cf5c06a52dbe4f9e9f43
3. Done. https://github.com/ArashFatahzade/alfacoins/commit/68ccf53229def1c85f3922c297318e061a243506
4. Done. https://github.com/ArashFatahzade/alfacoins/commit/8cff88ca6b82b9ce7654ba32ea0714ff0b26dee1
5. I will do that tomorrow.

PS: Your new [developer page](https://www.alfacoins.com/developers) locks a lot cleaner from the old one. Congrats.

**Comment by ALFAcoins** [comment]
Hi!

>1. Should I restore it?.

Yes, please.

>PS: Your new [developer page](https://www.alfacoins.com/developers) locks a lot cleaner from the old one. Congrats.

Thank you!

**Comment by iRhonin** [comment]
I have deployed the library on `pypi`. https://pypi.org/project/alfacoins/

**Comment by ALFAcoins** [comment]
Thanks, your pull request has been merged!

**Pull request merged**
